development:
  adapter: postgresql
  encoding: unicode
  database: recipe_app_development
  pool: 5
  host: localhost
  username: postgres
  password: Power003

test:
  adapter: postgresql
  encoding: unicode
  database: recipe_app_test
  pool: 5
  username: postgres
  password: Power003