default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development
  username: newton
  password: 12345

test:
  <<: *default
  database: recipe_app_test
  username: newton
  password: 12345

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>