development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: recipe_app_development
  pool: 5
  host: localhost
  username: newton
  password: 12345

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: recipe_app_test
  pool: 5
  username: newton
  password: 12345

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: recipe_app_production
  username: newton
  password: 12345